version: '3.9'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    #    network_mode: service:db
    volumes:
      - redis-data:/data

  triage-portal:
    image: triage-portal
    build:
      context: src
    command: python3 manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    container_name: triage-portal
    depends_on:
      redis:
        condition: service_started
    env_file:
      - ./src/.env-template

volumes:
  redis-data:
